### ISSUE TITLE
Lock status

### ISSUE THREAD

**Issue by MarcWiWi** [jeppesens/homebridge-glue#1]
Wouldn’t it be possible to get an automatic refresh on the lock status. When I browse the lock from the HomeKit app it fetches the current battery status so possibly this could be done for the lock status as well?

**Comment by jeppesens** [comment]
@MarcWiWi the lock state is not a thing that exists in Glue. I guess that it would be visible in their app as well if it was possible.

Maybe: One possibility is to somehow get the notifications and change the HomeKit state based on that

**Comment by jeppesens** [comment]
@MarcWiWi it should now be possible to have an updated state when the lock status is changed by the Glue app.

**Comment by MarcWiWi** [comment]
Thank you! Made my day!
