### ISSUE TITLE
Error loading plugin

### ISSUE THREAD

**Issue by macardi** [jeppesens/homebridge-glue#13]
Hi, I have tried the new version of the plugin without success. The log shows a number of errors when I restart Homebridge. I have an API that works when I test with the new plugin provided by Glue. I'm not sure if I'm doing something wrong or if there might be a bug. 

[Log](https://paste.ubuntu.com/p/c4B7yZwDhG/)

/Marcus

**Comment by jeppesens** [comment]
Thanks @macardi !

It was totally on my side and I have now updated the version on npm to 3.0.2 and it's working again!

**Comment by macardi** [comment]
Hi, thanks for a quick replay and fix! Now its working without errors when restarting Homebridge. However, all my Homebridge devices, including the Glue lock ends up with "No Response" in Homekit when enabling the plugin. As soon as I remove the plugin, all is back to normal. I have tried to play with the config, but the issue remains. Any ideas? 

/Marcus

**Comment by jeppesens** [comment]
Sorry for closing to quick, but that is also fixed now and works great in HomeKit for me! 

Thanks again @macardi

**Comment by macardi** [comment]
Yes, now its working! Thank you very much, really appreciate it!
