### ISSUE TITLE
Shows low battery in Home app

### ISSUE THREAD

**Issue by kongomannen** [jeppesens/homebridge-glue#16]
I’m running v3.0.5 and it shows low battery in the Home app. 

![03C6C587-6540-4BAD-9EC3-6992589E8F30](https://user-images.githubusercontent.com/12082075/108768365-dd47b200-7557-11eb-8bd8-8e7b9ec1e44b.png)

All looking good in the logs:
![56290369-079F-4B1A-8530-2B4D8489A7BE](https://user-images.githubusercontent.com/12082075/108768698-43343980-7558-11eb-87fb-8e74ac281688.png)

**Comment by siqiha** [comment]
This is still reproduceable under  v3.0.5

**Comment by siqiha** [comment]
Found the reason:
`callback( null, low ? hap.Characteristic.StatusLowBattery.BATTERY_LEVEL_NORMAL : hap.Characteristic.StatusLowBattery.BATTERY_LEVEL_LOW );`
order shoul be swapped

**Comment by jeppesens** [comment]
Well spotted! Easy fix and pushed to npm now
