### ISSUE TITLE
Issue with locking and unlocking all of a sudden

### ISSUE THREAD

**Issue by BiranHA** [jeppesens/homebridge-glue#32]
I have had the plugin running in HomeBridge for a year or so, and one day this week it failed to unlock. Did some troubleshooting and I get an error in HomeBridge:

[8/16/2023, 5:48:57 PM] Error: This callback function has already been called by someone else; it can only be called one time.
    at /var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:12:13
    at /var/lib/homebridge/node_modules/homebridge-glue/src/index.ts:192:17
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

I have no idea what could have happened. No changes in my system setup that I´m aware of. Any help would be greatly appreciated.

**Comment by jeppesens** [comment]
Unfortunately I cannot help, I keep the repo available but not using it myself. 
I'd happily review PRs to keep it working

**Comment by BiranHA** [comment]
Turs out it was an issue with Homebridge and not the plugin. Got it working again.
