### ISSUE TITLE
How to list and remove API keys 

### ISSUE THREAD

**Issue by arnonfarn** [jeppesens/homebridge-glue#33]
I believe I have added this before. But how do I list my current keys and how do I delete my old keys?

You have set a limit of 10 keys

Thanks /

**Comment by jeppesens** [comment]
This plugin should do some cleanup by itself https://github.com/jeppesens/homebridge-glue/blob/ce7fa17f2ed8a0750dcbd80b39758487e9865540/src/index.ts#L255-L262 you could reuse that logic to clean other api keys if'd want to

**Comment by arnonfarn** [comment]
Could you give me a one liner with curl for 2 things?

* List available keys
* Delete old keys

I couldn't really figured it out myself, but thanks for the feedback

**Comment by jeppesens** [comment]
@arnonfarn I recommend you to reach out to Glue or read/edit the code in this plugin. I'm no longer using it myself after switching to a different lock manufacturer.
