### ISSUE TITLE
Battery Status

### ISSUE THREAD

**Issue by VidasTouch** [jeppesens/homebridge-glue#5]
Får ej batteristatus och kan ej lägga till hub eller lock-id.

Skriver det enligt denna standarden:
GLXXX.DX1436.0403

**Comment by jeppesens** [comment]
Batteristatus verkar inte ha fungerat under gårdagen men ser ut att fungera i kväll. 

Det finns tyvärr ingen kontroll av Glues API:er utan det är ett ensidigt beroende. 

Testa gärna igen

**Comment by VidasTouch** [comment]
Fungerar fortfarande inte för mig tyvärr.

Måste man ha hub och lock-id specificerat för att batteristatus ska funka?

Och isåfall hur ska formatet se ut?

Skickat från mobil enhet

**Comment by jeppesens** [comment]
Du behöver inte specificera hub eller lock om du bara har ett lås. Kolla https://github.com/nilssontobias/homebridge-glue/blob/master/README.md
Däremot behöver du specificera username och password. 

Vad det gäller batteri så verkar det inte va relaterat till min kod utan till Glue, deras app beter sig liknande. 
![7CB40BAC-9C6D-4E07-AD21-75D41390D0A5](https://user-images.githubusercontent.com/29945975/71080574-b80a2780-218d-11ea-9b2f-e711190ebeff.png)
![80CE65F1-3441-4E08-966F-32B52368A58A](https://user-images.githubusercontent.com/29945975/71080575-b8a2be00-218d-11ea-83da-a49da395876c.png)

Stänger denna issue nu.

**Comment by VidasTouch** [comment]
Detta började funka efter jag tog ut och in batterierna från låset och kopplade ur och in wifi-adaptern! :)

Tack för detta plugin föresten, du är en hjälte!

Skickat från mobil enhet
