### ISSUE TITLE
Does it work with glue lock pro?

### ISSUE THREAD

**Issue by ghost** [jeppesens/homebridge-glue#6]
Does it work with glue lock pro? The newly released version

**Comment by jeppesens** [comment]
I don't know, I don't have any to test with nor is there any official API documentation from Glue. So you'd have to test and see. 
Interesting question though, so if you test it, please let us know if it works!

**Comment by Nicxe** [comment]
Take a look here https://github.com/jeppesens/homebridge-glue/issues/7

**Comment by jeppesens** [comment]
@malmentm the [latest version](https://www.npmjs.com/package/homebridge-glue) should work well for you.
