### ISSUE TITLE
Manual Unlock status from Glue Lock not registered 

### ISSUE THREAD

**Issue by Nicxe** [jeppesens/homebridge-glue#7]
The new [Glue Pro](https://www.gluehome.com/smart-pro) lock works with this plugin when you lock or unlock via the app or this plugin. However, the new lock also has a sensor that knows when you manually unlock the door, the status in the plugin is then "Setting status to Manual Unlock" and "Setting status to Manual Lock"  This is not registered as locked or unlocked from in the plugin. 

Except for that, it works flawlessly.

Plugin version 1.1.6

**Comment by jeppesens** [comment]
If the statuses is actually `Manual Lock` and `Manual Unlock` from Glue, then this PR [glue-lock-pro/support-manual-status](https://github.com/jeppesens/homebridge-glue/pull/8) should fix it for you. I cannot test it since I don't own a pro lock myself.
Could you test it @Nicxe ?

**Comment by Nicxe** [comment]
Sure I can test it @jeppesens The problem is I don´t know how to do it. I am using homebridge own image and have a UI to update and install the plugin. Have looked around in the terminal but can't even find where the plugin files are located. Any tips on how to it?

**Comment by jeppesens** [comment]
I see 3 alternatives here @Nicxe 
Without knowing exactly I have a guess. Based on [this ](https://github.com/oznu/homebridge-config-ui-x#installation-instructions) from homebridge repo. I think we can just install the package as root manually with `sudo npm i -g git+https://github.com/jeppesens/homebridge-glue.git#glue-lock-pro/support-manual-status` I guess you'd have to restart homebridge after that.

Alternatively:
- If that does not work you could find the location of the package with `sudo find / -type d -name 'homebridge-glue'`. _(It's slow but get's the job done)_
- If that does not help you it seems like homebridge is looking for packages in the locations mentioned [here](https://github.com/oznu/homebridge-config-ui-x/blob/d8aeb75031f1be1de09bb5fd89464b3b7df7d45c/src/modules/plugins/plugins.service.ts#L811) and for the last location you could use this `node -e "console.log(require('child_process').execSync('/bin/echo -n "$(npm --no-update-notifier -g prefix)/lib/node_modules"').toString('utf8'))"`

Remove the folders you found with homebridge-glue with `rm -rf {path}` and start from the top again 🙂

**Comment by Nicxe** [comment]
Thanks @jeppesens , I tried the change and I can confirm that is works, it now updates the staus when you manually lock or unlock.
